/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TareosRouteImport } from './routes/tareos'
import { Route as RendicionRouteImport } from './routes/rendicion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AsistenciaRouteImport } from './routes/asistencia'
import { Route as IndexRouteImport } from './routes/index'

const TareosRoute = TareosRouteImport.update({
  id: '/tareos',
  path: '/tareos',
  getParentRoute: () => rootRouteImport,
} as any)
const RendicionRoute = RendicionRouteImport.update({
  id: '/rendicion',
  path: '/rendicion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenciaRoute = AsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/login': typeof LoginRoute
  '/rendicion': typeof RendicionRoute
  '/tareos': typeof TareosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/login': typeof LoginRoute
  '/rendicion': typeof RendicionRoute
  '/tareos': typeof TareosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/login': typeof LoginRoute
  '/rendicion': typeof RendicionRoute
  '/tareos': typeof TareosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asistencia' | '/login' | '/rendicion' | '/tareos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asistencia' | '/login' | '/rendicion' | '/tareos'
  id: '__root__' | '/' | '/asistencia' | '/login' | '/rendicion' | '/tareos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenciaRoute: typeof AsistenciaRoute
  LoginRoute: typeof LoginRoute
  RendicionRoute: typeof RendicionRoute
  TareosRoute: typeof TareosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tareos': {
      id: '/tareos'
      path: '/tareos'
      fullPath: '/tareos'
      preLoaderRoute: typeof TareosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendicion': {
      id: '/rendicion'
      path: '/rendicion'
      fullPath: '/rendicion'
      preLoaderRoute: typeof RendicionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistencia': {
      id: '/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenciaRoute: AsistenciaRoute,
  LoginRoute: LoginRoute,
  RendicionRoute: RendicionRoute,
  TareosRoute: TareosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
